### ISSUE TITLE
server.py stuck on thread

### ISSUE THREAD

**Issue by fm64hylian** [off99555/Unity3D-Python-Communication#11]
Hi, I've been looking for something like this (I really felt the second to last question on your readme lol) I am trying to run a modified version of R-CNN mask from python to unity, the script is from [this repository](https://github.com/QuAITech/Image-And-Video-Potrait-Mode-Converter/tree/783be8db461e07219355daf653bb7b2856df0ea9) and just gets the image saved inside the unity project so I can display it later with opencv for unity.

so on `server.py`, I added some stuff (I am pretty new to python so it may be ugly)

```
import time
import zmq
import os
import threading

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")

#run on thread
def runMask(image):
    os.chdir("path/to/rcnn/mask")
    #I know there must be a better way to just call that function, I'm open to suggestions 
    cmd = "python ColorPopAndPotraitMode.py ColorPop --image "+image.decode()
    os.system(cmd)

while True:
    #  Wait for next request from client
    message = socket.recv()

    #message will be the name of the picture (path)
    print("Received request: %s" % message)
    print(os.getcwd())
    print("starting mask script")

    #starting thread to run mask (remember to put the ',' on args, else it would be treated as a tuple)
    thread = threading.Thread(target=runMask, args=(message,))
    thread.start()
    print("running mask")
    socket.send(b"... running mask ...")
    thread.join()

    #  Send reply back to client
    #  In the real world usage, after you finish your work, send your output here
    response = "done, "+os.getcwd()
    socket.send(response.encode())
```

I wrapped in a thread because is quite heavy and I wanted to make sure it would wait for the process to finish, however it gets stuck on this part forever until I close the window

```
2020-08-01 21:42:51.503401: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-08-01 21:42:51.757888: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-01 21:42:52.802719: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
```

I think it may have to do with tensorflow but if I run the exact same code in a different file without the server part, it works all right.
So, is there like a timeout or something that may provoke that from server.py?

btw the reason I am not using the Mask rcnn integrated on Opencv for unity is because it is using just a checkpoint (that much lighter .pb file) from the original model and the accuracy is not enough for our project, where we need to take body measurements, although we need that to run on android, and we are using GPU here, but that's for another day.

I running on windows 10, Nvidia GeForce GTX 1650 SUPER, python 3.8.3, tensorflow 2.2, keras 2.4, unity 2019.3.15

I know it is kind of unrelated, but if you have any questions, please let me know.

Thank you

**Comment by offchan42** [comment]
My repo teaches you how to send data to Unity. But it doesn't care about how you generate that data. You seem to have the problem generating that data which means that your issue is quite unrelated to this repo. But I will help for the sake of it.

It seems that you haven't identified clearly the problem that you are having. The first step is to identify your specific problem. Find out which line of code produce the issue. Ask yourself what you **expect** to happen. And what **actually** happened.
Use `print()` function to assist in your debugging.

My guess is that you are trying to read an image from Unity, run CNN in python, and then send the prediction back to Unity. So I would suggest you to inspect each step of this whole process. Check whether you got the image, first of all. Print the image's shape. After that, run the model, and see whether you get the prediction. Then check whether Unity got the prediction from ZeroMQ. Definitely one of these steps will be broken.

If any step of the process went wrong then at least you have **narrowed down the potential source of problem**. If you are not narrowing down the problem then that's not helping you fix the bug.

**Comment by fm64hylian** [comment]
thank you for your quick response, I am actually not sending anything back to unity (except for a message), the script generates the binary mask and places it on a folder, but I just restarted the PC and it went through the script, however at the end it threw this error:

```
Traceback (most recent call last):
  File "server.py", line 47, in <module>
    socket.send(response.encode())
  File "PATH\PythonStuff\envs\imageseg\lib\site-packages\zmq\sugar\socket.py", line 400, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 728, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 775, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Operation cannot be accomplished in current state
```
the final message from python wasn't received on unity.

**Comment by offchan42** [comment]
OK. Now that's a legit question that's based purely on the design of ZeroMQ request-reply pattern.
In ZeroMQ's request-reply pattern, you are expected to send a request and then wait for a reply. You must exactly do one request and then wait for exactly one reply. If you only send requests or only wait for replies, or send one request and then not wait for a reply, things will break. The state machine of ZeroMQ expects strongly that you follow its rule.

This means that in Unity, you must send a request and must also wait for a reply. In python, you must receive a request and send the reply. Both sides must do these things in a loop. If either `server` or `client` violate the rule, things break.

Let me know if that solves your problem.

**Comment by fm64hylian** [comment]
You are right, I am doing 2 socket.send from server.py but only 1 from unity, I will test it later to see how it goes.

thank you

**Comment by fm64hylian** [comment]
Ok, it went through smoothly, I removed the first socket.send and got rid of the thread on server.py. I am just starting to read the documentation on zeromq, and I know you mentioned that the server and client need to be reset or terminated to not crash unity. I check on client that you could do either `client.Disconnect()` or `client.Dispose()`, which one would you recommend to use after I got the response I wanted from the server? also should I disconnect manually form server.py as well to not crash unity?

Thank you

**Comment by offchan42** [comment]
![image](https://user-images.githubusercontent.com/15215732/89118722-1217ed00-d4d2-11ea-9e7e-70f104336403.png)
This code receives messages 10 times on Unity, and it works without crashing.
Just break after you got your message so that `NetMQConfig.Cleanup()` can be called. And that should be enough to end your client.

**Comment by fm64hylian** [comment]
yeah I'm calling both on unity and stopping the thread to see if the ports and everything was closed smoothly (I'm also doing `socket.close()`  and  `context.term()` on `server.py` just in case) I was wondering if there is a way to activate an environment from script so I don't have to call everything myself in the console, since I pretend to make an android build, I know its kind of unrelated to the repository, but do you know by chance how could we call server.py from unity? I'm using packages such as tensorflow and pycocotools, so I need python3 and can't use ironpython or python for unity since they do not support python 3 yet.

Any help would be appreciated, if not I'll just close the issue since we went out of scope here

**Comment by offchan42** [comment]
Try running the `python` command and environment activations using this method at the start of the unity scene.
https://stackoverflow.com/questions/1469764/run-command-prompt-commands
I've never tried it but it should work because it's similar to how you run commands in `cmd`.

And if you want to run multiple commands, try something like this: https://stackoverflow.com/questions/437419/execute-multiple-command-lines-with-the-same-process-using-net
You can do
```bash
conda activate YOUR_ENVIRONMENT
python server.py
```

When you quit the game, make sure to kill the `Process` that you have created.

Another thing is about packaging your python stuff, you need to learn how to freeze all your python packages into a folder so that it can be distributed with the Unity Build.  I've never tried that much. But I'm sure you could do it.
Here's the starting point:
https://docs.python-guide.org/shipping/packaging/

**Comment by fm64hylian** [comment]
That's perfect, I wasn't sure even I if did all that if it would work on an android build, I also tried to set an environment without anaconda with plain python since anaconda is much heavier. Thanks for the information about how to create python packages as well
