### ISSUE TITLE
Sending Images from Unity to Python

### ISSUE THREAD

**Issue by AlexYiningLiu** [off99555/Unity3D-Python-Communication#12]
Can you please share a short example of sending images from Unity to Python over the socket? The type of image is not of great importance, all that is required is for each image to come in sequentially with latency as low as possible. Thanks.

**Comment by offchan42** [comment]
To send any binary blob (not just image) through ZeroMQ, you just need to convert it to byte array first, then you can send and receive it properly. Once you receive the byte array, you can convert the byte array back to a numpy array.
You can choose one from many approaches to convert to byte array. 

For example, your byte array might contain 
- raw pixel values
- compressed JPEG image
- compressed PNG image. 

Choose one approach based on your requirement. If you prefer speed, compressing the image before sending might be a good idea (but you have to try all the approaches because compressing also takes time so you have to add compressing time to transfer time). If you want to send high quality image without it being modified, don't compress it using JPEG.

1. The image that you are sending from Unity, what format is it in?
2. Which conversion method do you want to use?

Suppose that your image is in the `Texture2D` format. And suppose you want to send an image in the `JPEG` format. Use https://docs.unity3d.com/ScriptReference/ImageConversion.EncodeToJPG.html and then send the result to ZeroMQ.

On the python side, read the byte array, then convert the JPEG bytes back to an image. An image in python is simply a numpy array. One way to convert JPEG byte array back to a numpy array is to use the `decode_jpeg` function from this package: https://pypi.org/project/simplejpeg/

That's it.

**Comment by AlexYiningLiu** [comment]
Thanks for the timely response. Will try it out.
