### ISSUE TITLE
Can be used for communication web browser and local machine?

### ISSUE THREAD

**Issue by Vishav3** [off99555/Unity3D-Python-Communication#17]
Thanks for the response to #16 ! I think the question was not clearly deliver to you (#16). The issue was not about type of data. The issue is that i need to communicate between web browser (the python server is running in the web browser (using Jupyter Notebook)) and unity (running on local machine). But i am not able to send data from browser to unity. Please give some guidance on that.

**Comment by offchan42** [comment]
This is a general networking question about ZeroMQ.
ZeroMQ doesn't care where you run your code. As long as both your processes (python server) and unity are communicating on the same port and they can see each other it will work. 
If it's not working, you probably done some bugs.  you need to debug it by producing minimal working code first.
Try communicating between your Jupyter process and another python process. 
By the way, it's not a good idea to run a server on Jupyter notebook.

**Comment by Vishav3** [comment]
I am very new to networking stuff. Your guidance will be helpful. There is no error showing up on either side but also communication is not happening.

**Comment by offchan42** [comment]
If communication is not happening, you need to tell me exactly which line of code is not performing what it needs to do. Print everything. With the information you gave me I have no exact idea to tell you what to do. My guidance is to suggest you to learn basic zeromq first and you will be able to debug on your own. when you ask questions you need to be very specific in order to get answer quickly without back and forth answering. 

You haven't done that maybe because you don't know it at all, so The official tutorial with no more than 10 lines of code will help you. 
By default I've already set the port of the server and client the same, so no need to change. 
But I'm not asking you to change, I'm asking you to create a new python client to replace unity. This is to see why it's not communicating by producing minimal working code first. Please learn ZeroMQ tutorial. You will see that it's very easy.

**Comment by Vishav3** [comment]
To explain the scenario. This is my Unity scene. Here the unity is sending message:


And this is where I am using python code in Jupyter notebook.  But the script keep running without receiving message.

I would like to add that the notebook is running inside the docker container of the server. And could be please share the link of ZeroMQ tutorial you are refering to?

**Comment by offchan42** [comment]
It's just official guide https://zguide.zeromq.org/

- have you tried without Jupyter notebook?
- please try to produce minimal working code that communicates between 2 python processes. Don't use unity. This becomes problem about docker networking stuff now. Which I guess is about setting the port properly when your call docker run command. But you should know this better because I don't know. If you don't know you need to learn how docker communicates with the external app. 

Again, it's better solved by minimal working code. Debug it. I don't know the answer right away.

**Comment by Vishav3** [comment]
No i have tried on local machine (between python and unity and that is working)
![image](https://user-images.githubusercontent.com/80038335/126834751-9066a275-b5e8-429d-b2a2-6f39603967b8.png)

**Comment by Vishav3** [comment]
I tried minimal working code that communicates between 2 python processes. Yes it works well! But python is not communicating with docker container. The code stops at receiving message. The port is configured properly when i call docker run command.

**Comment by offchan42** [comment]
1. Who is the server? Docker or your local host?
2. Which side is not receiving the message?
3. Did you try to run one simple python process on local host and another simple python process (Not jupyter) on your docker?
4. How do people usually communicate TCP between local host and docker? Try that method first before ZeroMQ. Because ZeroMQ is just a higher abstraction on TCP. If TCP works, so does ZeroMQ.

**Comment by Vishav3** [comment]
Sorry for asking so many things. The things are more complexed. But for simplicity, keep the docker container/Jupyter notebook aside. I just want to communicate between local host (i.e. my laptop using python) and webbrowser (i.e. python interpreter running). How can I do that using TCP communication?
This is browser side

This is on my local machine

But i am getting connection refused error. I am not understanding how to communicate between browser and laptop using TCP?
I need to make a persistent connection between a web browser and my python script.

**Comment by offchan42** [comment]
First of all, don't call that as running python from the browser. You are running Python process on someone else's computer server. The browser is irrelevant to the equation. 
Better call it as running python from an online IDE. 

Second, we cannot know whether the online IDE blocks the connection to the outside world or not. They can disallow you to create arbitrary sockets if they want. 

Third, create such TCP sockets on your machine and test 2 python processes first both in your machine. If it works and it doesn't work on that online IDE then they don't allow you to do it. There are many problems that could happen with networking e.g. firewall blocking, wrong IP address identification, etc. I cannot debug all that for you through this kind of back and forth messaging. Because even if it's team viewer and video call it will still take some time to debug it. You have to learn to do it yourself. That error message is very good point to Google and learn about all the possible causes for it to happen. 

Fourth, why are you trying to use an online IDE to connect to your unity client? Maybe you should try use another local computer as a server first?

I'm also not Pro at communication between 2 machines via networking, so you will have to debug it. This example repo is showing you how to communicate in one machine only. But it definitely can scale to any number of machines. 

Google how to communicate between python processes on different computer using python and go through that rabbit hole yourself.

**Comment by Vishav3** [comment]
Thanks for your all suggestions!
