### ISSUE TITLE
Can it send different info to different clients?

### ISSUE THREAD

**Issue by YanglanWang** [off99555/Unity3D-Python-Communication#18]
I have such scenario, in the python server, it uses class to update and calculate the instance' s state, then sends such state to corresponding client; in the client side, more than one clients need to communication with the server to get its one result and not interfere by others. Can your tool distinguish with different clients?

**Comment by offchan42** [comment]
There are 2 very common networking patterns: Request/Reply and Publish/Subscribe.
What you are talking about sounds like a Request/Reply pattern which is what this repo does.

In request/reply pattern, the server acts as a function. Any client can call this function and the function output will not get interfered from other clients.
For example, suppose the server is a square function. You send 5, it gives you 25. You send 10, it gives back 100. Server can handle any number of clients. Each client can request different values and no interference would happen because the server handle each request one by one.
ZeroMQ does this common pattern perfectly.

I think what you need to do is to think how to fit your code into request/reply pattern or pub/sub pattern. It's usually possible to do that.

**Comment by YanglanWang** [comment]
> There are 2 very common networking patterns: Request/Reply and Publish/Subscribe. What you are talking about sounds like a Request/Reply pattern which is what this repo does.
> 
> In request/reply pattern, the server acts as a function. Any client can call this function and the function output will not get interfered from other clients. For example, suppose the server is a square function. You send 5, it gives you 25. You send 10, it gives back 100. Server can handle any number of clients. Each client can request different values and no interference would happen because the server handle each request one by one. ZeroMQ does this common pattern perfectly.
> 
> I think what you need to do is to think how to fit your code into request/reply pattern or pub/sub pattern. It's usually possible to do that.

Thanks for your fast reply. I understand your example, but my scenario might be more complicated. 

Suppose in server side, there is a class with initial value self.i =0, then each time the client calls the class' s update function that do self.i=self.i+1 and return self.i. Actually there are two clients call such update function simultaneously, like when client1 calls update at third time, client2 calls update at first time. Can server distinguish between them and send correct value to corresponding client?

**Comment by offchan42** [comment]
Do you want to store one i value for each client? That's a stateful system. What you can do is to send client name along with the request and in the server create a dictionary pointing to each client's i value. 
Another solution is to just let client stores their own state and when requesting, you need to request with your state. 

I think it will be better if you tell your specific use case because there might be a better way.

**Comment by YanglanWang** [comment]
I don't know whether your tool can let me know the client's address. Then we can create threading for each client in the server side and don't need to store the i value.

**Comment by offchan42** [comment]
You might be able to read the client's address but that's probably not the
pattern that zeromq suggests. It prefers no identity when communicating. I
use zeromq in this repo. You can go learn more about it.

**Comment by YanglanWang** [comment]
Thanks a lot!!!
