### ISSUE TITLE
About send pictures

### ISSUE THREAD

**Issue by yumianhuli2** [off99555/Unity3D-Python-Communication#19]
Hello!
1、Should messages be sent only in child threads in order not to block the Unity main thread？
2、I need to send pictures,so  I used  client.SendFrame(Convert.ToBase64String(CameraHelper.CaptureFrame(Camera)));
But I got an error from unity:UnityException: get_targetTexture can only be called from the main thread

So How to send pictures by your plugin?Thank you!

**Comment by offchan42** [comment]
The child thread should be handling its own message queue and sending the message to the python server. You should not try to do this networking stuff in the main thread even if you can. It's a separation of concerns and will avoid you problems later.

You should create the base64 string from the main thread, then enqueue the string to the child thread's queue. The child thread then periodically dequeues the queue and send the base64 string to the python server.

If you want to always be sending the picture, I suggest that in an Update() function of a MonoBehavior, you can do the frame capturing and enqueue the base64 string. Because the Update() function will be called in the main thread.
