### ISSUE TITLE
about broadcast message

### ISSUE THREAD

**Issue by shoukailiang** [off99555/Unity3D-Python-Communication#20]
This is a good solution to my project. 
But I have another question. I have multiple clients(in unity) and How to write a broadcast message from one client to all other clients.I look forward to your reply.

**Comment by offchan42** [comment]
You probably want to use the pub-sub pattern of ZeroMQ. There is one publisher that publishes to many subscribers. But this repo only has the request-reply pattern example. You will need to learn a bit more about the pub-sub pattern, it's not much difficult.
Also, I suggest you to checkout BestHTTP2 package from Unity, you can use SocketIO protocol to communicate instead of ZeroMQ because it's better supported as it's a paid asset. There is also a dedicated SocketIO unity package. You can check out both.

**Comment by shoukailiang** [comment]
Oh, thank you for your reply
