### ISSUE TITLE
trolling users

### ISSUE THREAD

**Issue by sulyak** [off99555/Unity3D-Python-Communication#3]
The troubleshooting section says that killing the process using CTRL + C will break the server, and the example file "server.py" has a while True statement making the only way to stop the scrip (CTRL + C) crash the server.

**Comment by sulyak** [comment]
great work btw

**Comment by offchan42** [comment]
> The troubleshooting section says that killing the process using CTRL + C will break the server, and the example file "server.py" has a while True statement making the only way to stop the scrip (CTRL + C) crash the server.

You are absolutely right that the only way to stop the script is to use Ctrl+C or close the command prompt.
But I think you might misunderstand the issue that I was mentioning. I think the doc was not good enough so I changed it. Check this commit: https://github.com/off99555/Unity3D-Python-Communication/commit/2ef56acb4255ac19ac8c15bcb05ae2402cecdf66

The problem is that when you restart the server, the server won't reconnect to the old client anymore. You have to restart the client also.
