### ISSUE TITLE
Can this be used for communication between 2 pc?

### ISSUE THREAD

**Issue by Abdul-Mukit** [off99555/Unity3D-Python-Communication#6]
Hi,
Thank you for this great repo.
I am a beginner so my question might seem very trivial.

My project requires me to run a Unity project on one computer and run a python script in another computer. The two computers will be on the same network. We need to send data from the python script (pc-2) to Unity (pc-1). Can this be done using your repo?

The python script will output a matrix of 6 numbers. So we are thinking of using UDP. It is a PyTorch inferencing script. As the Unity pc's GPU will already be under stress we decided to run the deep learning inferencing on another pc.

**Comment by offchan42** [comment]
Yes. You can use this repo. But ZeroMQ is not UDP. It is a reliable message transfer.
For your use case, gRPC and SocketIO are also acceptable.
gRPC has an official Unity package and SocketIO also has Unity package (BestHTTP).
Use any of them according to your needs. If you just want something quick, go with ZeroMQ in this repo. But there is no official ZeroMQ package, you will encounter issues I mentioned in the **Known issues** section. You can use ZeroMQ but avoid using multiple clients.

I think you will not need to use multiple clients because you only have one job of outputting a matrix.

**Comment by Abdul-Mukit** [comment]
Thank you. It works well, I just tried it.
One question, when you said there is no official ZeroMQ package did you mean for C#?
On their webpage, I found codes for C# and python.

**Comment by offchan42** [comment]
I mean no official package for Unity. The NetMQ dll file inside this project is a hack.
